version: '3.8'

services:
  backend:
    build: .
    container_name: ema-backend-test
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PORT=5000
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=elliesdb
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:16
    container_name: ema-db-test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elliesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db:/docker-entrypoint-initdb.d

volumes:
  postgres_data: